export const RECEIPTS_LOADED = 'RECEIPTS_LOADED';
export const STATS_DATA_LOADED = 'STATS_DATA_LOADED';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';